name: VDrift

on: [push, pull_request]

jobs:
  test_Ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install_dependencies
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install scons libsdl2-dev libsdl2-image-dev libbullet-dev libvorbis-dev libcurl4-gnutls-dev
    - name: Build
      run: scons

  test_Windows:

    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: scons mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_image mingw-w64-x86_64-bullet mingw-w64-x86_64-curl mingw-w64-x86_64-libvorbis
    - name: Build
      run: scons

  test_MacOS:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: install_dependencies
      run: |
        brew install scons sdl2 sdl2_image bullet libvorbis curl
    - name: Build
      run: scons
